name: Priv8Remote Windows Build

on:
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Install vcpkg deps
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: |
          $VCPKG_ROOT/vcpkg install --triplet x64-windows-static --x-install-root="$VCPKG_ROOT/installed"
        shell: bash

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install bridge codegen
        run: cargo install flutter_rust_bridge_codegen --version 1.80.1

      - name: Generate bridge
        run: |
          cd flutter && flutter pub get && cd ..
          flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart

      - name: Build RustDesk
        run: python build.py --flutter
        shell: bash

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Priv8Remote-Windows
          path: |
            flutter/build/windows/x64/runner/Release/**
          retention-days: 30
