name: Priv8Remote Windows Build

on:
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Export cache vars
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: 120deac3062162151622ca4860575a33844ba10b

      - name: Install vcpkg deps
        run: |
          $env:VCPKG_ROOT = "C:\vcpkg"
          C:\vcpkg\vcpkg.exe install --triplet x64-windows-static --x-install-root="C:\vcpkg\installed"
        shell: pwsh
        working-directory: ${{ github.workspace }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install bridge codegen
        run: cargo install flutter_rust_bridge_codegen --version 1.80.1

      - name: Flutter pub get
        run: |
          cd flutter
          flutter pub get

      - name: Generate bridge
        run: flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart

      - name: Build
        run: python build.py --flutter
        shell: bash
        env:
          VCPKG_ROOT: C:\vcpkg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Priv8Remote-Windows
          path: flutter/build/windows/x64/runner/Release/
          retention-days: 30
